### ISSUE TITLE
Please provide .ufo sources for the vfb sources

### ISSUE THREAD

**Issue by alexmyczko** [polarsys/b612#11]
According to
```
medicalwei[m]> But if we need to convert vfb to ufo properly we might need FontLab Studio, or ask upstream to do that flavor...
```

I had to convert the vfbs using the non-free .exe from FontLab using wine to convert them to ufo files,
which I had troubles building from these sources for the Debian package:
http://phd-sid.ethz.ch/debian/fonts-b612/

Details: http://phd-sid.ethz.ch/debian/fonts-b612/fonts-b612-1.003%2Bgit20180121/debian/README.source

asked for at http://bugs.debian.org/919998

Problem details:
https://github.com/fonts/ufo2otf/issues/5
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920708

**Comment by thomaspaillot** [comment]
Hi, there's a [free cli vfb-›ufo converter](https://blog.fontlab.com/font-utility/vfb2ufo/) for Mac and Windows but we'll think about providing ufo source files in the future.

**Comment by alexmyczko** [comment]
It is not free as in free software. no sources, no right to modify and redistribute it... it is NOT free.

**Comment by thomaspaillot** [comment]
@alexmyczko You're right, the software is just free of charge…

**Comment by alexmyczko** [comment]
Meanwhile... https://packages.debian.org/unstable/fonts-b612

**Comment by thomaspaillot** [comment]
@alexmyczko Pull request #12 added UFO source files

**Comment by alexmyczko** [comment]
Many thanks! Can you also make it a release?
