### ISSUE TITLE
1.006 release broken under Windows.

### ISSUE THREAD

**Issue by Autotonic** [polarsys/b612#14]
Could be related #8 , i'm not really a font guy.
Left: 1.006 || Right: 1.005
![image](https://user-images.githubusercontent.com/13506877/54012374-d8f41580-4143-11e9-9745-9a1923868de6.png)

Edit: Worth mentioning this existed prior to 1.005 aswell

**Comment by thomaspaillot** [comment]
Thanks for reporting, should be fixed when pull request #13 will be merged.

**Comment by thomaspaillot** [comment]
@Autotonic Pull request #13 has been merged and should fix the rendering issue on Windows.

**Comment by Autotonic** [comment]
Yep fixed now for with #13 and #15 is good aswell. Thanks mate.
