### ISSUE TITLE
Wrong licence version

### ISSUE THREAD

**Issue by mavit** [polarsys/b612#16]
README.md says that Eclipse Public License version 1.0 applies, but version 2.0 is included in the repository.

**Comment by thomaspaillot** [comment]
You're right, we have updated the EPL license to the new 2.0 version but didn't update the README to reflect this change. There's already a PR #17 to fix the issue, it should be merged soon.

**Comment by thomaspaillot** [comment]
@mavit PR #17 has been merged, README.md is now up to date regarding the font licences.

**Comment by mavit** [comment]
Thanks!
