### ISSUE TITLE
Uppercase K and Q rendering at large sizes

### ISSUE THREAD

**Issue by tbolon** [polarsys/b612#28]
See screenshot below:

<img width="329" alt="image" src="https://github.com/polarsys/b612/assets/127185/4e07e895-0620-46c7-80f7-39a8b3ca7b0b">

Taken from [Google Font](https://fonts.google.com/specimen/B612?query=b612&preview.text=QKQKQKQKQK&preview.text_type=custom)

They are also visible when you browse [the official site](https://b612-font.com/):

<img width="260" alt="image" src="https://github.com/polarsys/b612/assets/127185/cfcd6c79-4b7b-456e-972b-6834253a1d64">

Perhaps it is expected, as it's really visible on large sizes.

**Comment by tbolon** [comment]
There seems to have a lot of strange corners in the web fonts, pick any variant and check the results on google font playground:

![image](https://github.com/polarsys/b612/assets/127185/96d193ff-e914-4b9a-b95e-cc440ffbc0d9)

**Comment by mariohamann** [comment]
If this is a bug, I hope it will never be fixed – I fell in love with the font because of those special details, which are shaping the font's character a lot and really shine in big sizes. 🙂

**Comment by tbolon** [comment]
Why not. But as the font primary goal was readability, I was surprised to see these details emerge. Maybe only small sizes were considered.

**Comment by tbolon** [comment]
After reading [multiple](https://poliseuse.wordpress.com/2019/02/15/b612/) [articles](https://intactile.com/projets/ameliorer-la-lisibilite-et-la-securite-dans-les-cockpits-d-airbus/), I am concluding that this was a deliberate choice, I will close this issue.

I think the readme is missing link to various articles on the web and the official website, which could help understanding the choices for this font.
