### ISSUE TITLE
Missing OpenType layout and TrueType hinting and kerning tables

### ISSUE THREAD

**Issue by moyogo** [polarsys/b612#8]
OpenType layout tables GPOS, GSUB and TrueType hinting tables LTSH, cvt, fpgm, hdmx and kern table have been missing from the TTFs after "Release new ttf files (1.005)" ac9a73542.

**Comment by thomaspaillot** [comment]
Hi, so this commit (1ed99157426c99df317d663a35159c7756bc0996) should have introduce the regression. We'll have a look at it and maybe @m4rc1e can tell us what changes this commit introduce.

**Comment by m4rc1e** [comment]
@thomaspaillot. Nope, I just generated the fonts in 1c1c6e4cd818ee3e19adb1844c302c488507f987 (commit before I started mastering) and they also lack the tables Denis reported.

**Comment by thomaspaillot** [comment]
Thanks for checking @m4rc1e, I'll will investigate this issue further and try to bring back the missing tables.

**Comment by thomaspaillot** [comment]
@moyogo Pull request #12 should have bring missing tables back, thanks for reporting the issue.
