### ISSUE TITLE
Rendering issue with right double quote in B612 Mono

### ISSUE THREAD

**Issue by Evotron** [polarsys/b612#9]
When I'm zoomed in, everything is fine:
![Zoomed in](https://i.imgur.com/jKFyf6v.jpg)

But if I zoom out just a little, the right double quote renders incorrectly:
![Zoomed out](https://i.imgur.com/gydoKJX.jpg)

This occurs in Sublime Text 3 as well:
![Sublime Text 3](https://i.imgur.com/ujgZ3Wc.jpg)

I'm using Windows 10 Pro.

**Comment by thomaspaillot** [comment]
@Evotron Should be fixed by pull request #12
